name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      - name: Install dependencies
        run: yarn install

      - name: Set up PostgreSQL
        uses: harmon758/postgresql-action@v1.2.0
        with:
          postgresql version: '13'

      - name: Run tests
        env:
          POSTGRESQL_URL: ${{ secrets.POSTGRESQL_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: yarn test

      - name: Build application
        run: yarn build

      - name: Deploy to production
        if: github.ref == 'refs/heads/main'
        run: |
          # Add your deployment commands here
          echo "Deploying to production..."
